//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDat.App.Resources.Texts
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilmDetailResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilmDetailResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmDat.App.Resources.Texts.FilmDetailResource", typeof(FilmDetailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        public static string Actors_ComboBox
        {
            get
            {
                return ResourceManager.GetString("Actors_ComboBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country_form
        {
            get
            {
                return ResourceManager.GetString("Country_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Czech Name.
        /// </summary>
        public static string Czech_name_form
        {
            get
            {
                return ResourceManager.GetString("Czech_name_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_button
        {
            get
            {
                return ResourceManager.GetString("Delete_button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_form
        {
            get
            {
                return ResourceManager.GetString("Description_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        public static string Directors_ComboBox
        {
            get
            {
                return ResourceManager.GetString("Directors_ComboBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration_form
        {
            get
            {
                return ResourceManager.GetString("Duration_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre_form
        {
            get
            {
                return ResourceManager.GetString("Genre_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_form
        {
            get
            {
                return ResourceManager.GetString("Name_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo_form
        {
            get
            {
                return ResourceManager.GetString("Photo_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating_form
        {
            get
            {
                return ResourceManager.GetString("Rating_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_button
        {
            get
            {
                return ResourceManager.GetString("Save_button", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title Photo URL.
        /// </summary>
        public static string URL_Photo_form
        {
            get
            {
                return ResourceManager.GetString("URL_Photo_form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review_tab
        {
            get
            {
                return ResourceManager.GetString("Review_tab", resourceCulture);
            }
        }
    }
}
